### ISSUE TITLE
The publishing date has successfully deceived my intuition about the Asp.net Core version that will be discussed

### ISSUE THREAD

**Issue by sadqiang** [csharpfritz/AspTravlerz#1]
In the late of 2016 I searched for books pertaining to asp.net core and I found this one but it had not been published yet. The book was scheduled to be available near September 2017 (as far as my memory is still good enough). After waiting for about 1 years, I noticed that the publishing date was changed to early 2018. Weirdly the total page numbers and price were also reduced significantly.

The angels on my shoulders said  that I have to be patient for a couple of months because the book will cover at least asp.net core 2.0.  If SignalR can be released at the end of 2017, the book will also cover it.
Unfortunately this book is only about Asp.net core 1.x. 

It is really disappointing. Online update is needed.

**Comment by EpsilonSigma** [comment]
Exactly... Same story here. The book should clearly state that it is about Core 1 and for those interested in deploying to Azure. I don't like to be misinformed.

**Comment by csharpfritz** [comment]
The review and update for this book took several months, during which the version of ASP.NET Core advanced past what we had already completed and delivered.  There was no ASP.NET Core 2 at that time, but the requirements of the publisher dictate that it needed to have a 2018 publication date.

We are discussing options for ASP.NET Core 2.

**Comment by torr6420** [comment]
Thanks for posting the sample code for the book, is it OK to use VS 2015? I
would like to install 2017, but I would prefer to uninstall 2015, but after
searching the web, some people had problems uninstalling VS 2015.
